spring.application.name=incidencias-api

spring.datasource.url=jdbc:postgresql://localhost:5432/incidenciasdb
spring.datasource.username=postgres
spring.datasource.password=alicia12

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
